package sun.tools.jar.resources;

import java.util.ListResourceBundle;

public final class jar_sv extends ListResourceBundle
{
  protected final Object[][] getContents()
  {
    return { { "error.bad.cflag", "för c-flaggan måste manifest- eller indatafiler anges." }, { "error.bad.eflag", "e-flaggan och manifest med attributet Main-Class kan inte anges \ntillsammans." }, { "error.bad.option", "Ett av alternativen -{ctxu} måste anges." }, { "error.bad.uflag", "för u-flaggan måste manifest-, e-flagg- eller indatafiler anges." }, { "error.cant.open", "kan inte öppna: {0} " }, { "error.create.dir", "{0} : Det gick inte att skapa någon katalog." }, { "error.illegal.option", "Ogiltigt alternativ: {0}" }, { "error.incorrect.length", "ogiltig längd vid bearbetning: {0}" }, { "error.nosuch.fileordir", "{0} : Det finns ingen sådan fil eller katalog." }, { "error.write.file", "Det uppstod ett fel vid skrivning till befintlig jar-fil." }, { "out.added.manifest", "extra manifestfil" }, { "out.adding", "lägger till: {0}" }, { "out.create", "    skapad: {0}" }, { "out.deflated", " ({0}% komprimerat)" }, { "out.extracted", "extraherat: {0}" }, { "out.ignore.entry", "ignorerar posten {0}" }, { "out.inflated", "expanderat: {0}" }, { "out.size", " (in = {0}) (ut = {1})" }, { "out.stored", " (0% lagrat)" }, { "out.update.manifest", "uppdaterad manifestfil" }, { "usage", "Användning: jar-filer {ctxui}[vfm0Me] [jar-fil] [manifestfil] [startpunkt] [-C-katalog] files ...\nAlternativ:\n    -c  skapa nytt arkiv\n    -t  lista innehållsförteckning för arkiv\n    -x  extrahera specifika (eller alla) filer från arkiv\n    -u  uppdatera befintligt arkiv\n    -v  generera ytterligare text för standardtext\n    -f  ange arkivfilens namn\n    -m  ta med manifestinformation från angiven manifestfil\n    -e  ange programstartpunkt för fristående program \n        som medföljer i en körbar jar-fil\n    -0  lagra endast (ingen zip-komprimering)\n    -M  skapa inte någon manifestfil för posterna\n    -i  generera indexinformation för de angivna jar-filerna\n    -C  ändra till den angivna katalogen och ta med följande fil\nOm en fil är en katalog bearbetas den rekursivt.\nNamnen på manifestfilen, arkivfilen och startpunkten anges i samma\nordning som m-, f- och e-flaggorna.\n\nExempel 1: Så här arkiverar du två klassfiler i ett arkiv vid namn classes.jar: \n       jar cvf classes.jar Foo.class Bar.class \nExempel 2: Använd en befintlig manifestfil (mymanifest) och arkivera alla\n           filer från katalogen foo/ i classes.jar: \n       jar cvfm classes.jar mymanifest -C foo/ .\n" } };
  }
}